### ISSUE TITLE
Small Issue

### ISSUE THREAD

**Issue by gregbenner** [petrbela/angular-magnific-popup#2]
It doesn't seem to be working...

**Comment by wodka** [comment]
well, at least I did not find any js code in here

I forked it and added at least a minimal directive:
https://github.com/wodka/angular-magnific-popup

**Comment by petrbela** [comment]
@wodka I can transfer the repo to you if you want to develop it further. The thing is, we've actually moved to React so I don't see myself working on this anymore...

**Comment by wodka** [comment]
Hi, yes why not :)

even if it's off topic - but why did you move to react - did you have issues with angular?

**Comment by petrbela** [comment]
@wodka Mostly what Daniel summed up here https://medium.com/este-js-framework/whats-wrong-with-angular-js-97b0a787f903. The (in)ability to tweak performance (especially on mobile) makes it hard to scale for big SPAs. IMHO they over-engineered many things, making it really hard for newbies to jump from "just using Angular" to actually being able to build directives (which is necessary if you want to build a large component-based application).

I still think Angular was a significant step towards building better web apps, and it came up with many concepts that are absolutely valid (TDD approach, composability). It's still a perfect solution if you want to build a complex app for desktop (and everyone on your team is experienced Angular developer).

However, React is built on a better architecture, easier to understand, easier to reason about. That's also why React Native can exist, why Flipboard could build [React Canvas](https://github.com/Flipboard/react-canvas), why Netflix is able to use [React on a TV without DOM](https://www.youtube.com/watch?v=eNC0mRYGWgc). When you have a superior architecture, you unlock totally new ways of doing things. And that's why we moved to React :)

**Comment by petrbela** [comment]
Hmm, @wodka I can't transfer the repo because you already have one with that name. Can you delete it, then I can make the transfer, and then you can merge with your changes?

**Comment by wodka** [comment]
just renamed it, so it should work now.

thx for the summary!

**Comment by petrbela** [comment]
> wodka already has a repository in the petrbela/angular-magnific-popup network

Apparently Github also checks if you've forked the repo, so it seems you'll need to delete that repo...

**Comment by wodka** [comment]
ok, I deleted it now (maybe it works this time^^)

**Comment by petrbela** [comment]
Cool! You should have a transfer request now.

**Comment by petrbela** [comment]
Great, looks like it worked. :)

**Comment by wodka** [comment]
@petrbela thx seems so
